import type { CoverageSummary, Zone } from "@/lib/citymind/types";
import type { District } from "@/lib/types";
import { districtLabel } from "@/data/seed/districts";
import { districtScore, openIncidentsIn, riskLevelIn } from "@/data/seed/derive";

// ─── CityMind AI — real Ramat Gan operations map ─────────────────────────────
// Unlike the earlier stylized rectangles, the geometry below is *real*:
//   • CITY_OUTLINE is the true municipal boundary of Ramat Gan (OpenStreetMap
//     relation 1382493, © OpenStreetMap contributors, ODbL), simplified.
//   • Each district footprint is a Voronoi cell seeded at the real coordinates
//     of that neighborhood and clipped to the municipal boundary — so the
//     districts tessellate, sit in their true relative positions (Shikun in the
//     narrow north, the National Park filling the south, Tel Hashomer in the
//     eastern panhandle, …) and together reproduce the real city silhouette.
// Coordinates are pre-projected (equirectangular, north-up) into the viewBox
// below; nothing is computed at runtime. Regenerated by scripts, not by hand.

/** SVG viewBox the paths below live in (portrait — matches the real city aspect). */
export const CITY_VIEWBOX = { w: 100, h: 144.43 } as const;

/** The true municipal boundary of Ramat Gan (drawn as the landmass silhouette). */
export const CITY_OUTLINE =
  "M 3.0 45.2 L 3.68 46.13 L 3.52 47.55 L 4.52 51.58 L 5.9 50.22 L 6.78 50.81 L 6.8 51.66 L 7.36 51.66 L 6.87 56.1 L 13.03 55.5 L 12.91 54.48 L 18.91 54.04 L 23.72 55.02 L 24.58 54.84 L 24.9 54.07 L 25.76 54.2 L 26.82 57.87 L 38.45 52.94 L 37.69 55.93 L 39.63 56.03 L 39.54 57.43 L 37.33 57.27 L 35.14 71.11 L 32.0 80.65 L 29.87 84.11 L 35.0 86.32 L 37.84 88.9 L 37.28 89.73 L 37.72 90.42 L 37.03 90.86 L 36.34 93.06 L 36.58 93.86 L 36.05 94.28 L 36.32 95.15 L 30.86 96.8 L 24.48 96.53 L 23.6 100.64 L 22.16 104.04 L 25.75 107.85 L 27.94 112.38 L 28.05 118.42 L 26.93 124.3 L 30.92 125.0 L 34.82 126.49 L 45.35 134.16 L 49.09 135.95 L 65.02 139.79 L 73.99 140.13 L 82.12 141.43 L 82.24 137.29 L 81.57 137.17 L 82.27 134.56 L 97.0 112.51 L 95.13 109.79 L 92.35 103.57 L 83.61 89.76 L 81.89 90.86 L 74.71 89.12 L 73.67 93.37 L 66.56 91.68 L 67.38 89.36 L 71.07 84.22 L 76.94 83.74 L 81.1 82.62 L 81.62 71.36 L 84.92 72.14 L 84.32 73.57 L 86.15 74.36 L 85.92 74.87 L 89.7 75.19 L 91.24 67.46 L 83.91 63.85 L 83.01 65.64 L 81.5 65.35 L 79.59 68.87 L 77.79 68.24 L 74.01 75.86 L 70.78 74.77 L 71.29 73.89 L 60.2 70.05 L 60.59 64.15 L 59.96 64.11 L 59.29 61.94 L 51.38 63.05 L 51.01 59.8 L 46.95 44.51 L 41.91 44.11 L 42.86 32.21 L 40.8 20.58 L 41.82 19.81 L 52.84 16.19 L 51.81 11.58 L 51.34 3.0 L 47.15 4.27 L 43.52 6.68 L 43.46 7.54 L 45.71 8.61 L 45.77 9.12 L 44.4 10.13 L 41.95 10.5 L 40.36 11.72 L 42.82 15.81 L 38.34 21.51 L 36.67 21.58 L 36.08 19.14 L 35.35 18.5 L 30.95 17.74 L 28.98 21.02 L 26.32 22.59 L 25.22 22.74 L 20.93 21.44 L 20.99 23.89 L 19.96 24.5 L 19.23 25.86 L 18.99 25.28 L 20.29 32.09 L 16.28 34.48 L 16.44 31.71 L 14.47 31.63 L 14.46 31.24 L 11.64 32.03 L 8.24 27.25 L 7.51 28.2 L 6.42 35.3 Z";

/**
 * Curated visual + coverage fields per zone. Geometry (path/label anchors) is the
 * real OSM-derived footprint — never hand-edit. `coveragePct` and `status` have no
 * source in the CSV and stay illustrative (see sync notes). The label, incident
 * count, risk level and sentiment are DERIVED below from the real complaint table,
 * so the map can't disagree with the sentiment panel or KPIs.
 */
interface ZoneGeometry {
  id: District;
  path: string;
  labelX: number;
  labelY: number;
  coveragePct: number; // ⚠ illustrative — not in source data
  status: Zone["status"]; // ⚠ illustrative — not in source data
}

const ZONE_GEOMETRY: ZoneGeometry[] = [
  {
    id: "Shikun Vatikim",
    path: "M 41.93 43.92 L 42.86 32.21 L 40.8 20.58 L 52.84 16.19 L 51.81 11.58 L 51.34 3.0 L 47.15 4.27 L 43.52 6.68 L 43.46 7.54 L 45.77 9.12 L 40.36 11.72 L 42.82 15.81 L 38.34 21.51 L 36.67 21.58 L 35.35 18.5 L 30.95 17.74 L 28.98 21.02 L 26.32 22.59 L 20.93 21.44 L 20.99 23.89 L 19.23 25.86 L 18.99 25.28 L 20.29 32.09 L 17.57 33.6 L 16.19 31.68 L 27.98 47.98 Z",
    labelX: 34.45,
    labelY: 28.88,
    coveragePct: 88,
    status: "covered",
  },
  {
    id: "Bursa District",
    path: "M 3.0 45.2 L 3.68 46.13 L 4.52 51.58 L 5.9 50.22 L 7.36 51.66 L 6.87 56.1 L 13.03 55.5 L 12.91 54.48 L 17.98 54.04 L 22.82 54.89 L 27.98 47.98 L 17.57 33.6 L 16.15 34.4 L 16.19 31.68 L 14.46 31.24 L 11.64 32.03 L 8.24 27.25 L 7.51 28.2 L 6.42 35.3 Z",
    labelX: 14.17,
    labelY: 44.13,
    coveragePct: 64,
    status: "at_risk",
  },
  {
    id: "Marom Nave",
    path: "M 22.82 54.89 L 25.76 54.2 L 26.82 57.87 L 38.45 52.94 L 37.69 55.93 L 39.63 56.03 L 39.54 57.43 L 37.33 57.27 L 34.6 72.41 L 56.2 85.88 L 57.5 85.49 L 67.77 72.63 L 60.2 70.05 L 60.59 64.15 L 59.96 64.11 L 59.29 61.94 L 51.38 63.05 L 46.95 44.51 L 41.93 43.92 L 27.98 47.98 Z",
    labelX: 46.23,
    labelY: 64.63,
    coveragePct: 71,
    status: "in_progress",
  },
  {
    id: "City Center",
    path: "M 34.6 72.41 L 32.0 80.65 L 29.87 84.11 L 35.55 86.7 L 37.84 88.9 L 37.3 89.68 L 56.2 85.88 Z",
    labelX: 40.93,
    labelY: 82.4,
    coveragePct: 84,
    status: "covered",
  },
  {
    id: "Ramat Chen",
    path: "M 37.3 89.68 L 37.72 90.42 L 37.03 90.86 L 35.89 95.56 L 29.3 96.93 L 24.48 96.53 L 22.16 104.04 L 26.52 109.04 L 28.01 113.33 L 37.0 119.18 L 55.97 86.04 Z",
    labelX: 37.85,
    labelY: 101.59,
    coveragePct: 76,
    status: "in_progress",
  },
  {
    id: "National Park",
    path: "M 40.6 130.33 L 45.35 134.16 L 54.23 137.4 L 65.02 139.79 L 73.99 140.13 L 82.12 141.43 L 82.24 137.29 L 81.57 137.17 L 82.23 135.07 L 57.5 85.49 L 55.97 86.04 L 37.0 119.18 Z",
    labelX: 58.71,
    labelY: 119.03,
    coveragePct: 58,
    status: "at_risk",
  },
  {
    id: "Tel Hashomer",
    path: "M 82.23 135.07 L 97.0 112.51 L 92.35 103.57 L 83.61 89.76 L 81.89 90.86 L 74.71 89.12 L 73.67 93.37 L 66.56 91.68 L 67.38 89.36 L 71.07 84.22 L 76.94 83.74 L 81.1 82.62 L 81.62 71.36 L 84.92 72.14 L 84.32 73.57 L 86.15 74.36 L 85.92 74.87 L 89.7 75.19 L 91.24 67.46 L 83.91 63.85 L 83.01 65.64 L 81.5 65.35 L 79.59 68.87 L 77.79 68.24 L 74.01 75.86 L 70.78 74.77 L 71.29 73.89 L 67.77 72.63 L 57.5 85.49 Z",
    labelX: 78.2,
    labelY: 99.14,
    coveragePct: 69,
    status: "at_risk",
  },
  {
    id: "Industrial Zone",
    path: "M 28.01 113.33 L 28.05 118.42 L 26.93 124.3 L 34.35 126.27 L 40.6 130.33 L 37.0 119.18 Z",
    labelX: 33.07,
    labelY: 121.68,
    coveragePct: 52,
    status: "uncovered",
  },
];

// The 8 operational zones — geometry curated, live numbers derived from real complaints.
export const CITY_ZONES: Zone[] = ZONE_GEOMETRY.map((g) => ({
  ...g,
  label: districtLabel(g.id),
  openIncidents: openIncidentsIn(g.id),
  riskLevel: riskLevelIn(g.id),
  sentiment: districtScore(g.id),
}));

export const COVERAGE_SUMMARY: CoverageSummary = {
  // DERIVED: average of the per-zone coverage (still illustrative until coverage has a real source).
  cleaningCoveragePct: Math.round(
    ZONE_GEOMETRY.reduce((s, z) => s + z.coveragePct, 0) / ZONE_GEOMETRY.length,
  ),
  zonesUnvisited: ZONE_GEOMETRY.filter((z) => z.status === "uncovered").length,
  slaRisksNext2h: 5, // ⚠ illustrative — not in source data
};
